os: linux
dist: xenial

language: python
python:
    - "3.6"
    - "3.7"

services:
    - docker

env:
    - MONGO=3.6
    - MONGO=4.0

before_install:
    - docker run -d -p 127.0.0.1:27017:27017 mongo:$MONGO

install:
    - travis_retry pip install --retries=30 --timeout=5 --no-cache-dir --disable-pip-version-check -U setuptools
    - travis_retry pip install --retries=30 --timeout=5 --no-cache-dir --disable-pip-version-check -U pip
    - travis_retry pip install --retries=30 --timeout=5 --no-cache-dir --disable-pip-version-check '.[asyncio,test]'

script:
    - py.test -v --cov yadm --cov-report term-missing

after_success:
    - coveralls
